### PR TITLE
Add efficient LPIPS computation

### PR DESCRIPTION
**Pull request by ingra14m**
I implemented an efficient LPIPS computation aligned with vanilla 3D-GS.

The time cost does not significantly increase (21s to 22s on Mip-360 bonsai, 3090). 

image

I also add ssim and lpips (vgg) in the final evaluation, which vanilla 3D-GS outputs in `metrics.py`.
image

### CODE REVIEW

**Comment by Linyou** [comment]
Hi @ingra14m,

Thanks for this PR! I've carefully reviewed the code and I think it looks good to merge :)

I made some updates to the codebase to use relative paths for better packaging. Would you mind rebasing your branch on top of main before merging?

**Comment by ingra14m** [comment]
Hi @Linyou, I have merged your latest commit.

And I have tested the current branch that I pulled request. It looks fine.
image

**Comment by ingra14m** [comment]
But I think the import path has something wrong.

In the launch.py, I need to add `sys.path.append("../../")` to successfully run the code.

**Comment by Linyou** [comment]
> But I think the import path has something wrong.
> 
> In the launch.py, I need to add `sys.path.append("../../")` to successfully run the code.

Have you try `pip install .` in the root directory of pointrix before running the projects? I think this should resolved the issue
You can also use `pip install -e .` to make local changes without needing to reinstall

**Pull request merged**
